### ISSUE TITLE
I use this to load CRZKD driver in 20H2,load success.But when Iconnect to the driver,then I got system-service-exception.

### ISSUE THREAD

**Issue by wexiuwexiu** [TheCruZ/kdmapper-1803-20H2#5]
![screenshot](https://user-images.githubusercontent.com/48826894/106616540-a27dda00-65a8-11eb-81de-be37b16f2277.png)

**Comment by TheCruZ** [comment]
This issue is related to CRZKD and not to kdmapper, CRZKD is little old and kdmapper now clears PiDDbCacheTable for you, try to remove this line from the driver: https://github.com/TheCruZ/CRZKD/blob/9d500885f3a95ab7c093ba675e95dcd5ec528f29/CRZKD/main.cpp#L162 the other option is use old kdmapper version or in any case create the issue in CRZKD project

**Comment by wexiuwexiu** [comment]
i use kd 20H2 to load crzkd but the pid and base i receive is incorrect.
![123](https://user-images.githubusercontent.com/48826894/108584332-4a7cfc80-7338-11eb-98c2-963d1a62150c.png)
